# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-13 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0006_userage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelling',
            old_name='rate',
            new_name='price',
        ),
    ]
